clear
black='\e[0;30m'
blue='\e[0;34m'
green='\e[0;32m'
cyan='\e[0;36m'
red='\e[0;31m'
purple='\e[0;35m'
brown='\e[0;33m'
lightgray='\e[0;37m'
darkgray='\e[1;30m'
lightblue='\e[1;34m'
lightgreen='\e[1;32m'
lightcyan='\e[1;36m'
lightred='\e[1;31m'
lightpurple='\e[1;35m'
yellow='\e[1;33m'
white='\e[1;37m'
nc='\e[0m'
echo
#Figlet nama
echo
echo
echo -e '\e[1;36m''                ###                         ####              '
echo -e '\e[1;36m''                #####                      #####              '
echo -e '\e[1;36m''                ##,###                    ###,;#              '
echo -e '\e[1;36m''                ##;;;##                 ####;ii#              '
echo -e '\e[1;36m''                ##it;i###              ###;iLGi#              '
echo -e '\e[1;36m''                ##ittiiG##           ####itLLiiD              '
echo -e '\e[1;36m''                ##ttttttt##;        ####itLLLii               '
echo -e '\e[1;36m''                ##tittttjj###      ###itffLLLi#               '
echo -e '\e[1;36m''                #jtitttttff##   ####tjfffffLi#               '
echo -e '\e[1;36m''                #jtiiittttfL#   ##Gjffffffffi#               '
echo -e '\e[1;36m''                ##tiiiiittt,#   ##ttjjjfffff;#               '
echo -e '\e[1;36m''                ##jiiiiiii,,#    ##jjjjjjfff;#               '
echo -e '\e[1;36m''                ##j;iiiiii,,#    ##jjjjjjjff;#               '
echo -e '\e[1;36m''                ##f;;iiiii,,#   ###jtjjjjjjf;#               '
echo -e '\e[1;36m''                ##f;;;;iiii,######jftttjjjj;,;               '
echo -e '\e[1;36m''                 ##L;i;;;;ii,,####jjtttttj,,;,                '
echo -e '\e[1;36m''                  ###.tt;;;;i;;ittjittttj,###                 '
echo -e '\e[1;36m''                    ##t,;;;;;iiiiiiiitt,#                    '
echo -e '\e[1;36m''                    ##j;;;;;;iiiiiiiit;#                    '
echo -e '\e[1;36m''            ###     ##f,;;;;;;;iiiiiii;#    ####K           '
echo -e '\e[1;36m''          ######    ##f,,,;;;;;;;iiiiii##  ###,####         '
echo -e '\e[1;36m''        #####L:##  ###L,,,,,;;ii;;;iiiit#####j,,,####       '
echo -e '\e[1;36m''     #####ffL,tt#####L,,,,,;;t#itt;;;iitt###jftt;;i####     '
echo -e '\e[1;36m''   #####jjji;;;tjjffL,,,,,;;#  ##tj;;;iijjjjfitttttttt####  '
echo -e '\e[1;36m'' #####tttiiii;;;;Lf,,,,,,;;#    ##j,;;;;iiiiiiiitttttjjf####'
echo -e '\e[1;36m''###,;ittiiiiiii;;;;;;;,,,;#      #Lj;;;;;;iiiiiiiitttttfLL##'
echo -e '\e[1;36m''#,,,ttttttiiiiiii;;;;;;,,;#      ##f,;;;;;;;iiiiiiiittttt,,,'
echo -e '\e[1;36m''###;;ittttttiiiiiii;;;;;;;##    ##jf,,;;;;;;;iiiiiiiii,,,G# '
echo -e '\e[1;36m''  ###iittttttiiiiiii;;;;;;i##  ###f:,,,,;;,;;;;iiiii,,,##   '
echo -e '\e[1;36m''     ##itjttttti,;;;ii;;;;ii#####jf,,,,,,,;;it;;;i,,,##     '
echo -e '\e[1;36m''       ###ffftt,;###iiii;;;tti#jjf,,,,,,#####tj,,,i#        '
echo -e '\e[1;36m''         ###LLG;#  ##ttiii;;;tjj,,,,,,,,:   ##,,##          '
echo -e '\e[1;36m''           K##G#    ##tiiiii;;;;;;,,,,,#     ###            '
echo -e '\e[1;36m''                    ##jiiiiii;;;;;;;,,,#                    '
echo -e '\e[1;36m''                    ##jtiiiiiii;;;;;;;,##                   '
echo -e '\e[1;36m''                   #####jtttiiiiiii;;;;;;;####                '
echo -e '\e[1;36m''                  #####jtttttt;;iitji;;;;;iE###               '
echo -e '\e[1;36m''                 ;#jjjfjjtttt,:####jjii;;;;tt,#               '
echo -e '\e[1;36m''                 ##jfjjjjjjt,;#   ##fiii;;;;;,#               '
echo -e '\e[1;36m''                 ##jffjjjjjj,#    ##fLiiii;;;,#               '
echo -e '\e[1;36m''                 ##jffffjjjj,#    ##ffiiiiii;,#               '
echo -e '\e[1;36m''                 ##fffffffjj;##   ##fitiiiiii,#               '
echo -e '\e[1;36m''                 ##ffffffffj,,#   ##Lttttiiii,#               '
echo -e '\e[1;36m''                 ##fLLfffff;;L#   ##iittttiii,:               '
echo -e '\e[1;36m''                 ##fLLLLff;;#      ##itttttti,,#              '
echo -e '\e[1;36m''                  #ffLLLLL;;#        f##jftttt;,#              '
echo -e '\e[1;36m''                 D#jfLLLi;##           ##fLtttt,#              '
echo -e '\e[1;36m''                 ##jfLLi;#              ##GGDtt,#              '
echo -e '\e[1;36m''                 ##jLii,#                 ##GGt,#              '
echo -e '\e[1;36m''                 ##jii#                    ##GG;#              '
echo -e '\e[1;36m''                 ##:i#                      ###t#              '
echo -e '\e[1;36m''                 ####                         ###              '
echo
figlet -f emboss Ariel sandy permana |lolcat
echo
echo -ne 'Today is:\t\t\e[1;31m' Sun Dec 15 22:18:29 WIB 2019; echo ''
echo -e 'Kernel Information: \t\e[1;31m' Linux 4.4.83 armv7l
echo
echo -e '\e[0;36m' 'Indonesian HaxID Team'
echo -e '\e[0;36m' ''the quieter you become, the more you able to hear''
echo
echo -e '\e[0;35m' '<|-----------------------------------------------------------------|>'
echo